spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/advanceJava_pw
    password: Hohwe1-daqjej-diktoz
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibrenate:
        format_sql: false
server:
  port: 9191
